<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SenPri" failures="2" tests="16" name="com.testcase.SignInPageTest" time="22.299" errors="0" timestamp="2023-05-21T11:27:54 EDT" skipped="0">
  <testcase classname="com.testcase.SignInPageTest" name="logintest_ValidData" time="1.841"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_ValidData" time="1.792"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_ValidData" time="1.498"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_ValidData" time="1.996"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_ValidData" time="1.936"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForUserName" time="1.080"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForUserName" time="1.859"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForUserName" time="1.076"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForUserName" time="1.035"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForUserName" time="1.109"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForPassword" time="1.820">
    <failure message="The following asserts failed:
	Testing_if_the_Null_value_for_Password_in_SigninPage_will_be_ACCEPETED expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Testing_if_the_Null_value_for_Password_in_SigninPage_will_be_ACCEPETED expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.testcase.SignInPageTest.logintest_NullDataForPassword(SignInPageTest.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logintest_NullDataForPassword -->
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForPassword" time="1.092"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForPassword" time="1.003"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForPassword" time="1.071"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForPassword" time="1.044"/>
  <system-out/>
  <testcase classname="com.testcase.SignInPageTest" name="logintest_NullDataForUserNameAndPassword" time="1.047">
    <failure message="Testing_if_the_Null_values_for_Username&amp;Password_in_SigninPage_will_be_ACCEPETED expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testing_if_the_Null_values_for_Username&Password_in_SigninPage_will_be_ACCEPETED expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at com.testcase.SignInPageTest.logintest_NullDataForUserNameAndPassword(SignInPageTest.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logintest_NullDataForUserNameAndPassword -->
  <system-out/>
</testsuite> <!-- com.testcase.SignInPageTest -->
